export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-zinc-50 dark:bg-black">
      <main className="mx-auto max-w-2xl px-6 py-16">
        <h1 className="text-2xl font-semibold text-black dark:text-zinc-50">
          Terms of Service
        </h1>
        <p className="mt-2 text-sm text-zinc-500">Last updated: September 2026</p>

        <div className="mt-8 flex flex-col gap-6 text-zinc-800 dark:text-zinc-200">
          <section>
            <h2 className="text-sm font-semibold uppercase tracking-wide text-zinc-500">
              What this tool is
            </h2>
            <p className="mt-2">
              This tool is a supplement that helps you understand a standard
              more deeply and see how your lesson relates to it. It is not a
              replacement for your own professional judgment, and it is not a
              guarantee that a lesson is or isn&apos;t aligned. You, the
              teacher, remain responsible for your own instructional
              decisions.
            </p>
          </section>

          <section>
            <h2 className="text-sm font-semibold uppercase tracking-wide text-zinc-500">
              AI-generated content
            </h2>
            <p className="mt-2">
              The analysis this tool produces is generated by an AI model and
              may occasionally be incomplete, miss something, or get
              something wrong. Review every result yourself before acting on
              it — the tool is here to support your expertise, not substitute
              for it.
            </p>
          </section>

          <section>
            <h2 className="text-sm font-semibold uppercase tracking-wide text-zinc-500">
              Acceptable use
            </h2>
            <p className="mt-2">
              This tool is for educators checking lesson and curriculum
              content against academic standards. Please don&apos;t submit
              student-identifying information, and don&apos;t use the tool
              for anything unlawful or outside its intended educational
              purpose.
            </p>
          </section>

          <section>
            <h2 className="text-sm font-semibold uppercase tracking-wide text-zinc-500">
              Your account
            </h2>
            <p className="mt-2">
              You&apos;re responsible for keeping your login credentials
              secure and for what happens under your account.
            </p>
          </section>

          <section>
            <h2 className="text-sm font-semibold uppercase tracking-wide text-zinc-500">
              No warranty, limited liability
            </h2>
            <p className="mt-2">
              This tool is provided as-is, without guarantees of any kind. To
              the fullest extent allowed by law, we aren&apos;t liable for
              decisions made based on the tool&apos;s output, or for any
              indirect or consequential damages arising from its use.
            </p>
          </section>

          <section>
            <h2 className="text-sm font-semibold uppercase tracking-wide text-zinc-500">
              Changes and termination
            </h2>
            <p className="mt-2">
              We may update these terms or the tool itself over time, and we
              may suspend or discontinue the service. We&apos;ll try to give
              reasonable notice of any major change.
            </p>
          </section>

          <section>
            <h2 className="text-sm font-semibold uppercase tracking-wide text-zinc-500">
              Governing law
            </h2>
            <p className="mt-2">
              These terms are governed by the laws of the State of New York.
            </p>
          </section>

          <section>
            <h2 className="text-sm font-semibold uppercase tracking-wide text-zinc-500">
              Contact
            </h2>
            <p className="mt-2">
              Questions about these terms can be sent to the email address
              associated with this project.
            </p>
          </section>
        </div>
      </main>
    </div>
  );
}
